# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alarm_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(350, 150)
        self.label_text = QtWidgets.QLabel(Form)
        self.label_text.setGeometry(QtCore.QRect(70, 20, 220, 30))
        self.label_text.setObjectName("label_text")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(250, 80, 80, 20))
        self.checkBox.setObjectName("checkBox")
        self.label_alarm = QtWidgets.QLabel(Form)
        self.label_alarm.setGeometry(QtCore.QRect(70, 70, 100, 40))
        self.label_alarm.setObjectName("label_alarm")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_text.setText(_translate("Form", "TextLabel"))
        self.checkBox.setText(_translate("Form", "CheckBox"))
        self.label_alarm.setText(_translate("Form", "TextLabel"))
